server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  application:
    name: customer   
  cloud:
    config:
      uri: http://localhost:8088
management:
  endpoint:
    refresh:
      enabled: true
