server:
  port: "8083"
  servlet:
    context-path: /api/v1
spring:
  application:
    name: admin
management:
  endpoint:
    refresh:
      enabled: true
message: "Hello Admin, How are you !"