server:
  port: 8083  
spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      enabled: true
      routes:
      - id: customer
        uri: lb://CUSTOMER
        predicates:
        - Path=/api/v1/customer/**
      - id: product
        uri: lb://PRODUCT
        predicates:
        - Path=/api/v1/product/**
          