server:
  port: "8081"
  servlet:
    context-path: /api/v1
spring:
  application:
    name: customer
management:
  endpoint:
    refresh:
      enabled: true
message: "Hello Customer, How are you !"